const CFG_ACCOUNT = module.exports;

CFG_ACCOUNT.UNAME = 'yxl123456';

CFG_ACCOUNT.UNAME_WRONG = 'DontExistUserName';

CFG_ACCOUNT.PWD = '123456';

CFG_ACCOUNT.UID = '70257';

CFG_ACCOUNT.ADMIN_NAME = 'admin';

CFG_ACCOUNT.ADMIN_PWD = '123456';