const CFG_SERVERS = module.exports;

CFG_SERVERS.IP = 'http://192.168.35.220';

CFG_SERVERS.I18N = 'zh_CN';

CFG_SERVERS.ADMIN_URL = `${CFG_SERVERS.IP}:3802`;

CFG_SERVERS.GATE_URL = `${CFG_SERVERS.IP}:3002`;

CFG_SERVERS.HALL_URL = `${CFG_SERVERS.IP}:3602`;

CFG_SERVERS.DB_SERVER = `${CFG_SERVERS.IP}:8888`;