module.exports = {
    tbl_account: ['id', 'jointype', 'who_invite_me', 'who_share_me', 'tempname', 'nickname', 'password', 'pwd_history', 'vip', 'login_count', 'logout_count', 'created_at', 'updated_at', 'last_online_time', 'salt', 'token', 'gold', 'pearl', 'weapon', 'skill', 'broke_times', 'first_login', 'day_reward', 'day_reward_adv', 'new_reward_adv', 'day_reward_weekly', 'vip_daily_fill', 'rmb', 'channel', 'channel_account_id', 'platform', 'vip_weapon_id', 'pfft_at', 'channel_account_name', 'channel_account_info', 'exp', 'level', 'level_mission', 'mission_daily_reset', 'mission_only_once', 'first_buy', 'activity_gift', 'heartbeat', 'heartbeat_min_cost', 'achieve_point', 'gold_shopping', 'weapon_skin', 'bonus', 'drop_reset', 'drop_once', 'comeback', 'vip_gift', 'weapon_energy', 'pirate', 'card', 'get_card', 'first_buy_gift', 'package', 'guide', 'guide_weak', 'active', 'active_daily_reset', 'active_stat_once', 'active_stat_reset', 'mail_box', 'free_draw', 'total_draw', 'roipct_time', 'aquarium', 'goddess', 'free_goddess', 'goddess_free', 'goddess_ctimes', 'goddess_crossover', 'goddess_ongoing', 'figure', 'redress_no', 'test', 'rank_in_friends', 'over_me_friends', 'charm_rank', 'charm_point', 'sex', 'city'],
    tbl_account_server:['uid', 'sid', 'login_time'],
    tbl_account_sign:['id', 'month_sign'],
    tbl_activity:['id', 'created_at', 'gift_id', 'description', 'name', 'icon', 'price', 'item', 'condition', 'value', 'starttime', 'endtime', 'buycount', 'version', 'revoke', 'discount'],
    tbl_admin_auth:['id', 'page', 'description', 'parent', 'level', 'valid'],
    tbl_admin_role:['id', 'rname', 'description', 'auth_ids', 'valid'],
    tbl_admin_user:['id', 'uname', 'salt', 'password', 'token', 'created_at', 'updated_at', 'role', 'valid'],
    tbl_ai:['id', 'created_at', 'last_log_id', 'wpTimesP', 'firstFireSecondsP', 'noFireQuitChanceP', 'fishTimesP', 'sameFishAverageDtP', 'targetShiftTimesP', 'normalStaySecondsP', 'brokenStaySecondsP', 'iceSkillTimesP', 'lockSkillChanceP', 'callSkillTimesP', 'holdChanceP', 'holdAverageSecondsP', 'waitAverageSecondsP', 'holdingQuitChanceP'],
    tbl_ai_log:['id', 'account_id', 'log_at', 'wpTimes', 'firstFireSeconds', 'noFireQuitChance', 'fishTimes', 'sameFishAverageDt', 'targetShiftTimes', 'normalStaySeconds', 'brokenStaySeconds', 'iceSkillTimes', 'lockSkillChance', 'callSkillTimes', 'holdChance', 'holdAverageSeconds', 'waitAverageSeconds', 'holdingQuitChance'],
    tbl_aquarium:['id', 'total_level', 'updated_at'],
    tbl_bind_log:[ 'id', 'account_id', 'nickname', 'log_at'],
    tbl_cd_key:[ 'id', 'created_at', 'cd_key', 'action_id', 'account_id', 'use_time'],
    tbl_change_log:['id', 'orderid', 'sn', 'uid', 'name', 'phone', 'address', 'created_at', 'ship_at', 'cid', 'catalog', 'count', 'cost', 'itemname', 'status', 'thingnum', 'way', 'card_num', 'card_pwd', 'icon'],
    tbl_channel_create:['id', 'channel_uid', 'created_at', 'updated_at', 'count'],
    tbl_channel_login:['id', 'channel_create_id', 'log_at'],
    tbl_daily_statistics:['id', 'account_id', 'created_at', 'date', 'login_count', 'logout_count', 'gold_gain', 'gold_cost', 'gold_shop_count', 'gold_shop_amount', 'pearl_gain', 'pearl_cost', 'pearl_shop_count', 'pearl_shop_amount', 'skill_gain', 'skill_cost', 'account_levelup', 'weapon_levelup_exp', 'weapon_levelup_pearl', 'game_time'],
    tbl_drop_log:['id', 'account_id', 'log_at', 'drop_key', 'times'],
    tbl_drop_serverlimit:['key', 'limit_type', 'limit_count', 'current_value', 'platform'],
    tbl_exp_log:['id', 'account_id', 'added_exp', 'total_exp', 'duration'],
    tbl_goddess:['id', 'max_wave', 'updated_at', 'week_reward', 'week_rank'],
    tbl_gold:['id', 'account_id', 'current_total', 'total_gain', 'total_cost', 'shop_count', 'shop_amount'],
    tbl_gold_log:['id', 'account_id', 'log_at', 'gain', 'cost', 'total', 'duration', 'scene', 'nickname', 'level'],
    tbl_img:['id', 'web_url', 'local_url'],
    tbl_link_log:['id', 'uid', 'linked_at', 'api', 'id', 'id', 'uid', 'linked_at', 'api', 'id', 'id', 'uid', 'linked_at', 'api', 'id', 'id', 'uid', 'linked_at', 'api'],
    tbl_link_sum:['time', 'online_count', 'link_count', 'sid'],
    tbl_login_log:['id', 'account_id', 'log_at', 'nickname', 'level'],
    tbl_logout_log:['id', 'account_id', 'log_at', 'nickname'],
    tbl_mail:['id', 'type', 'title', 'content', 'reward', 'sendtime'],
    tbl_operation:['id', 'cfg_id', 'desc', 'value', 'type'],
    tbl_order:['id', 'sn', 'game_order_id', 'channel_order_id', 'game_account_id', 'channel_account_id', 'created_at', 'updated_at', 'goods_id', 'goods_number', 'money', 'status', 'channel_cb', 'channel'],
    tbl_pearl:['id', 'account_id', 'current_total', 'total_gain', 'total_cost', 'shop_count', 'shop_amount'],
    tbl_pearl_log:['id', 'account_id', 'log_at', 'gain', 'cost', 'total', 'scene', 'nickname'],
    tbl_propose:['id', 'uid', 'text', 'time', 'like_uids', 'like_count'],
    tbl_rankgame:['id', 'updated_at', 'win', 'fail', 'points', 'rank', 'unfinish', 'box', 'box_timestamp', 'first_box', 'season_count', 'season_win', 'season_box', 'season_first_win', 'is_season_reward', 'winning_streak'],
    tbl_rankgame_log:[`id`,`time`,`player1`,`wait_time1`,`rank1`,`bullet_score1`,`used_bullet1`,`nuclear_score1`,`nuclear_exploded1`,`player2`,`wait_time2`,`rank2`,`bullet_score2`,`used_bullet2`,`nuclear_score2`,`nuclear_exploded2`,`result`],
    tbl_room:['plazaid', 'roomid'],
    tbl_shop_log:['id', 'account_id', 'log_at', 'item_id', 'item_type', 'item_amount', 'nickname', 'price', 'order_id'],
    tbl_skill_log:['id', 'account_id', 'skill_id', 'gain', 'cost', 'total', 'log_at', 'nickname'],
    tbl_social:[`id`,`invite_friends`,`share_friends`,`invite_progress`,`invite_reward`,`share_status_0`,`share_status_1`,`share_status_2`,`enshrine_status`,`share_top_gold`,`share_top_rank`,`invite_daily`],
    tbl_stat_day:['id', 'log_date', 'created_at', 'new_account', 'login_count', 'active_count', 'drr', 'wrr', 'mrr', 'shop_time_count', 'shop_account_count', 'shop_tpa', 'shop_pafft', 'shop_paffd', 'shop_pta', 'shop_arpu', 'shop_arrpu'],
    tbl_stat_hour:['id', 'created_at', 'new_account', 'login_count', 'account_count'],
    tbl_switch:['id', 'match_on', 'msgboard_mgmt', 'cik_on', 'cdkey_on'],
    tbl_weapon_log:['id', 'account_id', 'log_at', 'level', 'type', 'level_up', 'nickname', 'vip_weapon_id'],
};