module.exports = {
	1: "登录界面",
	2: "模式选择界面",
	3: "游戏战斗场景(Fire)",
	4: "商城充值(Rechage)",
	5: "小游戏(Minigame)",
	6: "破产领取",
	7: "所有场景",
	8: "武器升级(Weapon Upgrade)",
	9: "技能购买(Buy Skin)",
	10: "场景消耗",
	11: "奖金抽取(Goldfish Draw)",
	12: "日常领取(Mission Daily)",
	13: "成就领取(Misson Once)",
	14: "海盗任务领取(Mission Pirate)",
	15: "捕鱼掉落(Drop)",
	16: "VIP礼包购买",
	17: "限时礼包",
	18: "商城金币购买(Buy Gold)",
	19: "皮肤购买(Buy Skin)",
	20: "保卫女神挑战(Goddess Challenge)",
	21: "女神解锁(Goddess Unlock)",
	22: "女神升级(Goddess Upgrade)",
	23: "被偷取(Be Stolen)",
	24: "宠物鱼升级或者解锁(Petfish Unlock or Upgrade)",
	25: "合成(Item Mix)",
	26: "宠物鱼领取奖励(Petfish Reward)",
	27: "核弹领取奖励2",
	28: "排位赛开宝箱",
	29: "激光领取奖励(Laser)",
	30: "排行榜奖励(Chart Reward)",
	31: "活动抽奖(Active Draw)",
	32: "打赏奖励",
	33: "翻盘基金购买",
	34: "月签奖励和消耗(补签消耗钻石)(Sign Reward)",
	35: "分享奖励(Share Reward)",
	36: "活动任务(Active Mission)",
	37: "活动兑换(Active Exchange)",
	38: "活动充值回馈(Active Recharge)",
	39: "邀请好友",
	40: "开启礼盒",
	41: "首充奖励(First Rechage Reward)",
	42: "月卡奖励(Card Reward)",
	43: "收藏奖励",
	44: "话费券兑换",
	45: "出售物品获取金币(Sell Item)",
	46: "使用物品获取金币(Use Item)",
	47: "邮件领取(Mail Reward)",
	48: "购买月卡消耗(Buy Card)",
	49: "核弹消耗",
	50: "抽奖消耗",
	51: "炸弹鱼爆炸所得(Fish Bomb)",
	52: "闪电鱼点击所得(Fish Flash)",
	53: "VIP每日福利",
	54: "礼品码领取(Giftcode)",
	55: "女神互动(Goddess Interact)",
	56: "玩家取消实物兑换(Cik Cancel)",
};