var _TXT_CONTENT_EN = {
    txt_title_cache_account: "Cache Account Query",
    txt_content_cache_account: "Cache Account Query.",
    txt_title_cache_mail: "Cache Mail Query",
    txt_content_cache_mail: "Cache Mail Query.",
    txt_title_query_cfgs: "Query Configs",
    txt_content_query_cfgs: "Query Configs.",
    txt_title_gold_log: "Gold Log",
    txt_content_gold_log: "Gold Log.",
    txt_title_mail_rank: "Mail Rank",
    txt_content_mail_rank: "Mail Rank.",
    txt_title_reset: "Reset",
    txt_content_reset: "Reset data for daily or weekly.",
    txt_title_retention: "Retention",
    txt_content_retention: "Retention.",
    txt_title_modify_account: "Modify User Data",
    txt_content_modify_account: "Modify User Data.",
    txt_title_kick: "Kick User",
    txt_content_kick: "Kick User.",
    txt_title_tester: "Test Auth & Forbidden",
    txt_content_tester: "Test Auth & Forbidden.",
    txt_title_systime: "Systime Change",
    txt_content_systime: "Systime Change.",
    txt_title_chart_generate: "Chart Generate",
    txt_content_chart_generate: "Chart Generate.",
};
exports.TXT_CONTENT_EN = _TXT_CONTENT_EN;

var _TXT_CONTENT_CN = {
    txt_title_cache_account: "内存用户数据查询",
    txt_content_cache_account: "内存用户数据查询，输入用户数据和字段(可选), 返回用户数据.",
    txt_title_cache_mail: "内存邮件数据查询",
    txt_content_cache_mail: "内存邮件数据查询.",
    txt_title_query_cfgs: "查询服务器配置文件",
    txt_content_query_cfgs: "查询服务器配置文件.",
    txt_title_gold_log: "金币日志",
    txt_content_gold_log: "金币日志.",
    txt_title_mail_rank: "补发排行榜邮件",
    txt_content_mail_rank: "补发排行榜邮件.",
    txt_title_reset: "重置数据",
    txt_content_reset: "重置数据: 重置每日数据和每周数据, 并可指定玩家进行设置.",
    txt_title_retention: "手动生成留存数据",
    txt_content_retention: "手动生成留存数据, 设置开始日期和结束日期, 点击按钮生成(慎用, 不要频繁点击).",
    txt_title_modify_account: "修改玩家数据",
    txt_content_modify_account: "修改玩家数据(同时改变内存和数据库).",
    txt_title_kick: "游戏升级时踢出玩家",
    txt_content_kick: "游戏升级时踢出玩家.",
    txt_title_tester: "测试权限管理和账号重置",
    txt_content_tester: "测试权限管理和账号重置(同样的QQ号会重新注册并进入游戏引导).",
    txt_title_systime: "服务器系统时间修改",
    txt_content_systime: "服务器系统时间修改.",
    txt_title_chart_generate: "定时生成排行榜奖励",
    txt_content_chart_generate: "定时生成排行榜: 每日奖励, 每周奖励及数据重置, 每月奖励及数据重置.",
};
exports.TXT_CONTENT_CN = _TXT_CONTENT_CN;