var _TXT_CONTENT_EN = {
    txt_title_signup: "SignUp & SignIn",
    txt_content_signup: "SignUp & SignIn.",
    txt_title_setting: "Setting",
    txt_content_setting: "Setting: Set url & aes.",
    txt_title_account: "Account",
    txt_content_account: "Account: Logout, Get Info.",
    txt_title_gold: "Gold",
    txt_content_gold: "Gold Test.",
    txt_title_pearl: "Pearl",
    txt_content_pearl: "Pearl Test.",
    txt_title_skill: "Skill",
    txt_content_skill: "Skill Test.",
    txt_title_weapon: "Weapon",
    txt_content_weapon: "Weapon Test.",
    txt_title_shop: "Shop",
    txt_content_shop: "Shop Test.",
    txt_title_cfg: "Config",
    txt_content_cfg: "Config Test.",
    txt_title_bind: "Bind",
    txt_content_bind: "Bind Test.",
    txt_title_changepwd: "Change Password",
    txt_content_changepwd: "Change Password Test.",
    txt_title_sdk: "SDK Test",
    txt_content_sdk: "SDK Test.",
    txt_title_pay: "Pay Simulate",
    txt_content_pay: "Pay Simulate.",
    txt_title_order: "Order Test",
    txt_content_order: "Order Test.",
    txt_title_update_account: "Update Account.",
    txt_content_update_account: "Update Account: ",
    txt_title_broadcast: "Broadcast",
    txt_content_broadcast: "Broadcast Test.",
    txt_title_cdkey: "CD-KEY Use",
    txt_content_cdkey: "CD-KEY Use Test.",
    txt_title_active: "Active Test",
    txt_content_active: "Active Test.",
    txt_title_mail: "Mail Test",
    txt_content_mail: "Mail Test.",
    txt_title_msgboard: "Msg Board Test",
    txt_content_msgboard: "Msg Board Test.",
};
exports.TXT_CONTENT_EN = _TXT_CONTENT_EN;

var _TXT_CONTENT_CN = {
    txt_title_signup: "注册和登录",
    txt_content_signup: "注册和登录相关测试，包括临时账户，昵称账户，渠道账户相关操作.",
    txt_title_setting: "设置",
    txt_content_setting: "设置连接地址和加密方式.",
    txt_title_account: "账户相关",
    txt_content_account: "退出登录，获取账户相关信息.",
    txt_title_gold: "金币测试",
    txt_content_gold: "金币记录测试，在数据表tbl_gold_log中增加记录.",
    txt_title_pearl: "珍珠测试",
    txt_content_pearl: "珍珠记录测试，在数据表tbl_pearl_log中增加记录.",
    txt_title_skill: "技能测试",
    txt_content_skill: "技能测试, 在数据表tbl_skill_log中增加记录.",
    txt_title_weapon: "武器测试",
    txt_content_weapon: "武器测试, 在数据表tbl_weapon_log中增加记录.",
    txt_title_shop: "商城测试",
    txt_content_shop: "商城测试, 在数据表tbl_shop_log中增加记录.",
    txt_title_cfg: "配置测试",
    txt_content_cfg: "配置测试, 拉取配置表, 拉取配置文件.",
    txt_title_bind: "绑定账号",
    txt_content_bind: "绑定账号测试t.",
    txt_title_changepwd: "修改密码",
    txt_content_changepwd: "修改密码测试.",
    txt_title_sdk: "SDK测试",
    txt_content_sdk: "SDK测试: 测试白鹭接入SDK的相关API, 第一个参数为API的名字, 第二个参数为API需要处理的全部参数.",
    txt_title_pay: "支付模拟",
    txt_content_pay: "模拟客户端调用渠道接口后渠道回调游戏提供的回调地址.",
    txt_title_order: "订单测试",
    txt_content_order: "订单测试: 获取订单号，并轮询检测订单状态.",
    txt_title_update_account: "更新账户.",
    txt_content_update_account: "更新账户: 更新的信息包括经验值(exp),...",
    txt_title_broadcast: "公告测试",
    txt_content_broadcast: "公告测试: 拉取和客户端主动通知",
    txt_title_cdkey: "CD-KEY使用",
    txt_content_cdkey: "CD-KEY使用 Test.",
    txt_title_active: "活动测试",
    txt_content_active: "活动测试.",
    txt_title_mail: "邮件测试",
    txt_content_mail: "邮件测试.",
    txt_title_msgboard: "留言板测试",
    txt_content_msgboard: "留言板测试: 留言，点赞",
};
exports.TXT_CONTENT_CN = _TXT_CONTENT_CN;