module.exports = {
    PASSWORD: 1,
    GOLD: 2,
    PEARL: 3,
    ITEM: 4,
    IS_FREEZE: 5,
    IS_BLOCKED: 6,
    MONTH_CARD: 7,
    MONTH_CARD_REWARD: 8,
    SKILL: 9,
    FIRST_BUY_GIFT: 10,
    RMB: 11,
    MAIL_BOX: 12,
    FREE_DRAW: 13,
    TOTAL_DRAW: 14,
    BONUS: 15,
    VIP_GIFT: 16,
    VIP_DAILY_REWARD: 17,
    WEAPON: 18,
    CARD: 19,
    GET_CARD: 20,
};