module.exports = {
    newweapon_weapons: require('./cfgs/newweapon_weapons'),
    shop_card: require('./cfgs/shop_card'),
    item_item: require('./cfgs/item_item'),
    rankgame: require('./cfgs/rankgame'),
    string: require('./cfgs/string'),
    treasure: require('./cfgs/treasure'),
    change: require('./cfgs/change'),
    daily_dailypast: require('./cfgs/daily_dailypast'),
    vip: require('./cfgs/vip'),
    common: require('./cfgs/common'),
    scene: require('./cfgs/scene'),
    daily: require('./cfgs/daily'),
    goddess: require('./cfgs/goddess'),
    drop: require('./cfgs/drop'),
    active: require('./cfgs/active'),
    mission: require('./cfgs/mission'),
};