module.exports = {
    getChangeLog: require('./getChangeLog'),
    confirmChange: require('./confirmChange'),
    cancelChange: require('./cancelChange'),
    queryJackpot: require('./queryJackpot'),
    queryServerPeriod: require('./queryServerPeriod'),
    queryPlayer: require('./queryPlayer'),
    getCashData: require('./getCashData'),
    getProfitChart: require('./getProfitChart'),
    changeCatchRate: require('./changeCatchRate'),
    changeQueryServerPeriod: require('./changeQueryServerPeriod'),
    getPlayerData: require('./getPlayerData'),
    modifyPlayerData: require('./modifyPlayerData'),
    getFireData: require('./getFireData'),
    getSceneCatchRateList: require('./getSceneCatchRateList'),
    modifySceneCatchRate: require('./modifySceneCatchRate'),
};